/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as CategoriaCategoriaRouteImport } from './routes/categoria.$categoria'
import { Route as ModeloIdRouteImport } from './routes/modelo.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaCategoriaRoute = CategoriaCategoriaRouteImport.update({
  id: '/categoria/$categoria',
  path: '/categoria/$categoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeloIdRoute = ModeloIdRouteImport.update({
  id: '/modelo/$id',
  path: '/modelo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contactos': typeof ContactosRoute
  '/categoria/$categoria': typeof CategoriaCategoriaRoute
  '/modelo/$id': typeof ModeloIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contactos': typeof ContactosRoute
  '/categoria/$categoria': typeof CategoriaCategoriaRoute
  '/modelo/$id': typeof ModeloIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contactos': typeof ContactosRoute
  '/categoria/$categoria': typeof CategoriaCategoriaRoute
  '/modelo/$id': typeof ModeloIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contactos' | '/categoria/$categoria' | '/modelo/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contactos' | '/categoria/$categoria' | '/modelo/$id'
  id: '__root__' | '/' | '/contactos' | '/categoria/$categoria' | '/modelo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactosRoute: typeof ContactosRoute
  CategoriaCategoriaRoute: typeof CategoriaCategoriaRoute
  ModeloIdRoute: typeof ModeloIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$categoria': {
      id: '/categoria/$categoria'
      path: '/categoria/$categoria'
      fullPath: '/categoria/$categoria'
      preLoaderRoute: typeof CategoriaCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelo/$id': {
      id: '/modelo/$id'
      path: '/modelo/$id'
      fullPath: '/modelo/$id'
      preLoaderRoute: typeof ModeloIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactosRoute: ContactosRoute,
  CategoriaCategoriaRoute: CategoriaCategoriaRoute,
  ModeloIdRoute: ModeloIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
